--- #YAML:1.0
name:               Syntax-Highlight-Engine-Kate
version:            0.05
abstract:           a port to Perl of the syntax highlight engine of the Kate texteditor.
author:
    - Hans Jeuken <haje <at> toneel <dot> demon <dot> nl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
